Fix /Users/lat/Dropbox/lat-build/circura/app/.meteor/local/cordova-build/platforms/android/src/com/pylonproducts/wifiwizard/WifiWizard.java:55: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing cordova.getActivity() to cordova.getActivity().getApplicationContext() [WifiManagerLeak]         super.initialize(cordova, webView);                                ^
   Explanation for issues of type "WifiManagerLeak":
   On versions prior to Android N (24), initializing the WifiManager via
   Context#getSystemService can cause a memory leak if the context is not the
   application context. Change context.getSystemService(...) to
   context.getApplicationContext().getSystemService(...).